### ISSUE TITLE
`example/example.ipynb` fails due to `KeyError`

### ISSUE THREAD

**Issue by maouw** [childmindresearch/bids2table#28] opened 2024-04-11 21:59 UTC
https://github.com/childmindresearch/bids2table/blob/c3f4c12d97eb7bfb8f18da8ce4150ec3a2348493/example/example.ipynb fails at https://github.com/childmindresearch/bids2table/blob/c3f4c12d97eb7bfb8f18da8ce4150ec3a2348493/example/example.ipynb#L2627-L2637 .

Code:
```python
filtered = (
    tab
    .filter("task", contains="rest")
    .filter("sub", items=["04", "08"])
    .filter("RepetitionTime", 2.5)
)

filtered
```

Output:
```
{
	"name": "KeyError",
	"message": "'Invalid key RepetitionTime; expected a valid BIDS entity or metadata field present in the dataset'",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ../bids2table/table.py:184, in BIDSTable.filter(self, key, value, items, contains, regex, func)
    183 if key[:1].isupper():
--> 184     col = self.flat_meta[key]
    185 # Long name entity

File ../.venv/lib/python3.12/site-packages/pandas/core/frame.py:4102, in DataFrame.__getitem__(self, key)
   4101     return self._getitem_multilevel(key)
-> 4102 indexer = self.columns.get_loc(key)
   4103 if is_integer(indexer):

File ../.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py:417, in RangeIndex.get_loc(self, key)
    416 if isinstance(key, Hashable):
--> 417     raise KeyError(key)
    418 self._check_indexing_error(key)

KeyError: 'RepetitionTime'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[14], line 5
      1 filtered = (
      2     tab
      3     .filter(\"task\", contains=\"rest\")
      4     .filter(\"sub\", items=[\"04\", \"08\"])
----> 5     .filter(\"RepetitionTime\", 2.5)
      6 )
      8 filtered

File ../bids2table/bids2table/table.py:192, in BIDSTable.filter(self, key, value, items, contains, regex, func)
    190         col = self.flat[key]
    191 except KeyError as exc:
--> 192     raise KeyError(
    193         f\"Invalid key {key}; expected a valid BIDS entity or metadata field \"
    194         \"present in the dataset\"
    195     ) from exc
    197 if value is not None:
    198     mask = col == value

KeyError: 'Invalid key RepetitionTime; expected a valid BIDS entity or metadata field present in the dataset'"
}

**Comment by clane9** [comment] 2024-07-10 17:49
Closing since not able to reproduce. We can reopen later if it appears again.

**Closed by clane9** 2024-07-10 17:49 UTC
